### ISSUE TITLE
yarn still error!

### ISSUE THREAD

**Issue by xinsuinizhuan** [TypeFox/theia-xtext-sprotty-example#11]
warning "workspace-aggregator-790b66c9-a186-4975-9f3e-3da1abac5ac0 > browser-app

    @theia/cli > @theia/application-manager > font-awesome-webpack > less-loader@
    2.2.3" has incorrect peer dependency "less@^2.3.1".
    [4/4] Building fresh packages...
    [-/11] ⠈ waiting...
    [11/11] ⠈ @theia/java
    [-/11] ⠁ waiting...
    [-/11] ⠁ waiting...
    error D:\Eclipse\eclipse_theia\src_run\theia-xtext-sprotty-example-master\theia
    node_modules@theia\java: Command failed.
    Exit code: 1
    Command: node ./scripts/download-jdt-ls.js
    Arguments:
    Directory: D:\Eclipse\eclipse_theia\src_run\theia-xtext-sprotty-example-master\t
    heia\node_modules@theia\java

**Comment by kittaakos** [comment]
> Command: node ./scripts/download-jdt-ls.js

Sometimes downloading the JDT LS timeouts, that had caused the error when you ran `yarn`. It is unfortunate, but there is not much we can do here. If you believe we should support retrials in case of timeout, please open a [new issue in Theia](https://github.com/theia-ide/theia/issues/new).

I am closing this.
