### ISSUE TITLE
Update documentation with Theia prerequisites

### ISSUE THREAD

**Issue by kdvolder** [TypeFox/theia-xtext-sprotty-example#15]
I'm trying to follow the build instructions from here: 
https://github.com/TypeFox/theia-xtext-sprotty-example#local

I have:
```
$ node --version
v10.16.2
```
and
```
$ yarn --version
1.17.3
```

When I get to the step to run yarn to build the theia extension...

```
$ yarn
yarn install v1.17.3
....
error /home/kdvolder/git/theia-xtext-sprotty-example/theia/node_modules/native-keymap: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /home/kdvolder/git/theia-xtext-sprotty-example/theia/node_modules/native-keymap
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.16.2 | linux | x64
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/home/kdvolder/git/theia-xtext-sprotty-example/theia/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/kdvolder/git/theia-xtext-sprotty-example/theia/node_modules/native-keymap/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/kdvolder/git/theia-xtext-sprotty-example/theia/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/kdvolder/.node-gyp/10.16.2/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/kdvolder/.node-gyp/10.16.2',
gyp info spawn args   '-Dnode_gyp_dir=/home/kdvolder/git/theia-xtext-sprotty-example/theia/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/kdvolder/.node-gyp/10.16.2/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/kdvolder/git/theia-xtext-sprotty-example/theia/node_modules/native-keymap',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
Package x11 was not found in the pkg-config search path.
Perhaps you should add the directory containing `x11.pc'
to the PKG_CONFIG_PATH environment variable
No package 'x11' found
Package xkbfile was not found in the pkg-config search path.
Perhaps you should add the directory containing `xkbfile.pc'
to the PKG_CONFIG_PATH environment variable
No package 'xkbfile' found
gyp: Call to 'pkg-config x11 xkbfile --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/kdvolder/git/theia-xtext-sprotty-example/theia/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.15.0-55-generic
gyp ERR! command "/usr/bin/node" "/home/kdvolder/git/theia-xtext-sprotty-example/theia/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /home/kdvolder/git/theia-xtext-sprotty-example/theia/node_modules/native-keymap
```

**Comment by kdvolder** [comment]
Found solution here: 
https://github.com/Microsoft/vscode/issues/72106#issuecomment-483518461

```
sudo apt install libx11-dev libxkbfile-dev libxkbfile-dev
```

**Comment by kittaakos** [comment]
Thank you for reporting this and leaving the solution here as a comment, @kdvolder. 🙏

This requirement is documented here: https://github.com/TypeFox/theia-xtext-sprotty-example/blob/master/README.md#local

I am closing this.

**Comment by kdvolder** [comment]
> This requirement is documented here

Really? I don't see it. All I see listed as requirement is 

- node >= 10.x, < 12.x
- yarn > 1.3
- Java > 1.8

I see no mention of any of this extra stuff that I had to install to avoid the nodegyp errors.

**Comment by kittaakos** [comment]
There is the link which will navigate you to the prerequisites of Theia where the native dependencies are declared for the Linux platform. The reason I do not want to add all these into the troubleshooting section again explicitly is that then we have to do it for every single project built on the top of Theia. Thoughts?

If you disagree, and you think we should include it, I am more than happy to review your PR enhancing the documentation.

edit: wording

**Comment by kdvolder** [comment]
> There is the link which will navigate ...

Ah indeed, I missed that. I understand you don't want to repeat/duplicate intformattion. In that case it may be better to actually not repeat *any* of it. Having a partial requirement list here and then rest of it hidden in a link is actually more confusing than just having the link alone.

So my sugestion is, keep the link, and delete the incomplete list of requirements.

Anyhow, utlimately It is really up to you to decide what to do with this feedback.

**Comment by kittaakos** [comment]
> So my sugestion is, keep the link, and delete the incomplete list of requirements.

👍 I will rework the documentation based on your feedback. I am glad you found the solution for your issue and posted here. Thank you!
