### ISSUE TITLE
How to debug xtext language server

### ISSUE THREAD

**Issue by tjroamer** [TypeFox/theia-xtext-sprotty-example#21]
This is rather a question than an issue: Is there a way to debug the language server? Using "yarn start" in browser-app folder, the java process cannot be debugged. Thanks.

**Comment by kittaakos** [comment]
1. Clone the repository and use the `assemble` Gradle task to build the LS and prepare the projects for Eclipse:
```
cd language-server/ \
&& ./gradlew clean assemble
```

2. Import the Gradle project into Eclipse:

![Screen Shot 2019-10-07 at 08 30 07](https://user-images.githubusercontent.com/1405703/66289696-a8dd4280-e8dd-11e9-8cf7-7191a36dd982.jpg)

![Screen Shot 2019-10-07 at 08 30 25](https://user-images.githubusercontent.com/1405703/66289750-d924e100-e8dd-11e9-81fb-93b1dc6b05b9.jpg)


3. Build Theia:
```
cd ../theia/ \
&& yarn
```

4. Start the browser-based application in debug mode:
```
yarn --cwd ./browser-app/ start:debug
```

5. Start the LS from Eclipse in debug mode:
![Screen Shot 2019-10-07 at 08 33 43](https://user-images.githubusercontent.com/1405703/66289781-f0fc6500-e8dd-11e9-9ec5-fa7b451ea8a7.jpg)

![Screen Shot 2019-10-07 at 08 33 50](https://user-images.githubusercontent.com/1405703/66289822-01acdb00-e8de-11e9-8fec-daeaff2a7230.jpg)

![Screen Shot 2019-10-07 at 08 33 58](https://user-images.githubusercontent.com/1405703/66289850-12f5e780-e8de-11e9-94a2-b63461c798f1.jpg)

6. Open your browser on `localhost:3000` and open the `theia-xtext-sprotty-example/ws-theia` location as your Theia workspace root.

7. Hit a breakpoint:
![Screen Shot 2019-10-07 at 08 35 01](https://user-images.githubusercontent.com/1405703/66289954-49336700-e8de-11e9-86db-e2ed501ece44.jpg)

**Comment by tjroamer** [comment]
@kittaakos Thanks a lot for your detailed explanation. Very helpful! It saved me a lot of time.
