### ISSUE TITLE
How to setup more than one diagram types for same model

### ISSUE THREAD

**Issue by tjroamer** [TypeFox/theia-xtext-sprotty-example#24]
Hi,
I created a DSL with graphical rendering based on your example. I got a requirement to have different views (diagram types) for the same textual model, such that the user can right-click on the text file and select which view she wants to show. Currently, my approach is to use a single diagram server on the server side and send different models to client depending on the diagram type. Correspondingly, on the client side, I had to create for each diagram type the following:
- a diagram server subclassed from **LSTheiaDiagramServer**
- a diagram manager (declares label for menu, and iconClass)
- a subclass of **DiagramConfiguration** for binding
- create a container in di.config.ts

I see a lot of duplicated code in TypeScript. If I would need to have an additional diagram type, I would create these classes again and again. In addition, I cannot create different layout approaches for these diagram types, since there is only one diagram server on the server side, different configurations regarding **needsClientLayout** and **needsServerLayout** in di.config.ts will create problems.

What would be the best way to do it? An small example would be very appreciated.
Thanks in advance for your support.

**Comment by JanKoehnlein** [comment]
Sorry for the late answer.

On the server side, there is one Guice injector for each Xtext language. You can register multiple diagram types in the [DiagramServerFactory](https://github.com/TypeFox/theia-xtext-sprotty-example/blob/fd9a1ff7daa0d6a5f616622f94128598e4d62ae2/language-server/io.typefox.examples.theia.states.ide/src/main/java/io/typefox/examples/theia/states/ide/diagram/StatesDiagramServerFactory.xtend#L10), and then extract the `diagramType` from the `context` in the diagram generator to generate a different kind of SModel.

On the client side, each diagram (instance!) gets its own Inversify container, configured by the config for its `diagramType`. You can directly re-use implementations of all services by binding the same classes. Each container will create their own instances of these. In addition, you can use the usual ways (inheritance or composition) to extract common code for re-use.

**Comment by tjroamer** [comment]
thanks a lot for your answer. Yes, it solved my puzzle.
