### ISSUE TITLE
How can I get the correct Xtext DSL？

### ISSUE THREAD

**Issue by username123wy** [TypeFox/theia-xtext-sprotty-example#25]
We have five Ecore files for our model, but when we use eclipse tools to automatically convert the Ecore file to Xtext, there are two problems as follows, we would like to consult you.
![10](https://user-images.githubusercontent.com/35055195/71085293-1fe26180-21d2-11ea-8552-cb375cc1fea5.JPG)

![15](https://user-images.githubusercontent.com/35055195/71085837-5f5d7d80-21d3-11ea-86ec-79bd6fe97f80.JPG)

![11](https://user-images.githubusercontent.com/35055195/71085796-4785f980-21d3-11ea-9b16-f896bd871096.jpg)

there is a file named ‘GenerateMyDsl.mwe2’ be created, but when we click ‘running as mwe2 Workflow’ it has some errors.
![14](https://user-images.githubusercontent.com/35055195/71085571-caf31b00-21d2-11ea-9ed9-b061db376018.JPG)

How to solve this problem?

**Comment by JanKoehnlein** [comment]
Not related to this repo, neither to Sprotty or Theia. Please file such issues in Xtext or ask in the [Xtext forum](https://www.eclipse.org/forums/index.php/f/27/)
