### ISSUE TITLE
Renaming is not working correctly

### ISSUE THREAD

**Issue by NiklasRentzCAU** [TypeFox/theia-xtext-sprotty-example#3]
The rename feature is not working as intended and renames a different state than selected.
This can be reproduced as follows:

(0. Apply the fix from pull request #2 so this example can actually be built)
1. Create a new file such as Test.sm.
2. write this basic code in the file:
`statemachine test
`
3. Open the diagram view
4. Hover in the diagram and create a new state with the popup box by clicking on "new State"
5. Same as step 4
6. Double click on the state1 in the diagram and rename the element in the new popup box to e.g. "foo"

This causes the state0 to be renamed to foo and not the state1 as was intended.

**Comment by kittaakos** [comment]
I could not reproduce the defect with #10.

![theia-xtext-sprotty-example_GH_3](https://user-images.githubusercontent.com/1405703/60489764-6a643600-9ca5-11e9-8559-3aae583550ab.gif)

**Comment by kittaakos** [comment]
@NiklasRentzCAU, can you please try it again from the `master`? Thank you!

**Comment by NiklasRentzCAU** [comment]
I cannot reproduce this issue either anymore with the current master. However, I found some other issues after just playing around with the new master for a bit of which one still fits the title of this issue:


* Create a new file such as Test.sm.
* write this basic code in the file:
  `statemachine test `
* Open the diagram view
* Hover in the diagram and create two new states with the popup box by clicking on "new State" twice
* Click on the "new Event" text once as well.

When you try to connect state0 to state1 in the diagram by dragging the arrowhead, it won't connect. First, you have to manually move the `event event0` line in front of the state definitions and add a blank line between them, so the code now looks like this:
`
statemachine test
event event0

state state0
state state1
`

Only then the connection works. I don't know if this is intentional that the events have to be stated before the states with a blank line in between, but even if that is the case they should also be automatically added that way.

The other problem again is with renaming. Do the same steps as above, but before adding the connection, rename state1 to foo. Now when connecting state0 to the now renamed state foo in the diagram there will be a connection to the now undefined state1 added in the text. As the state is already renamed, this behavior is not expected.
