### ISSUE TITLE
Allow diagram widget to be displayed as a preview widget

### ISSUE THREAD

**Issue by debovema** [TypeFox/theia-xtext-sprotty-example#5]
Hi,

I'm trying to display a Diagram in a preview pane as defined in the [preview package](https://github.com/theia-ide/theia/tree/master/packages/preview).

My idea was to generate the Diagram widget using [the ```createWidget``` method of the ```DiagramManager``` class](https://github.com/eclipse/sprotty-theia/blob/6b63891b81c8a249e2519de328d57393972a4dc0/src/theia/diagram-manager.ts#L92) then using [the ```getSvgElement``` method of the ```DiagramWidget``` class](https://github.com/eclipse/sprotty-theia/blob/6b63891b81c8a249e2519de328d57393972a4dc0/src/theia/diagram-widget.ts#L159) in [the ```renderContent``` method of the ```PreviewHandler``` interface](https://github.com/theia-ide/theia/blob/e147cf39c7f484374b7ec0cd0d04958c3ef00bca/packages/preview/src/browser/preview-handler.ts#L37).

However, it seems that the widget must be added to the shell and activated to actually generate the SVG content of the diagram, for instance using [the ```doOpen``` method of the ```DiagramManager``` class](https://github.com/eclipse/sprotty-theia/blob/6b63891b81c8a249e2519de328d57393972a4dc0/src/theia/diagram-manager.ts#L46). And we should avoid that when displaying the diagram in a preview pane.

Is it possible ? Or does it require some change in sprotty-theia library ?

Thanks for your help !

**Comment by JanKoehnlein** [comment]
See https://github.com/eclipse/sprotty-theia/issues/37
